
version: '2'

services:

    zookeeper:
        image: hyperledger/fabric-zookeeper
        env_file: .env
        ports:
            - 2181
            - 2888
            - 3888

    kafka:
        image: hyperledger/fabric-kafka
        environment:
            - KAFKA_LOG_RETENTION_MS=-1
            - KAFKA_MESSAGE_MAX_BYTES=103809024
            - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
            - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
            - KAFKA_DEFAULT_REPLICATION_FACTOR=3
            - KAFKA_MIN_INSYNC_REPLICAS=2
        env_file: .env
        ports:
            - 9092

    orderer:
        image: hyperledger/fabric-orderer
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=deployment_behave
            - ORDERER_HOME=/var/hyperledger/orderer
            - ORDERER_GENERAL_LOGLEVEL=debug
            - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LEDGERTYPE=ram
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/configs/orderer.block
            - CONFIGTX_ORDERER_ORDERERTYPE=solo
            - CONFIGTX_ORDERER_BATCHSIZE_MAXMESSAGECOUNT=10
            - CONFIGTX_ORDERER_BATCHTIMEOUT=2s
            - CONFIGTX_ORDERER_ADDRESSES=[127.0.0.1:7050]
            # TLS settings
            - ORDERER_GENERAL_TLS_ENABLED=true
            - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/tls/server.key
            - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/tls/server.crt
            - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/tls/ca.crt]
            - ORDERER_TLS_CLIENTAUTHREQUIRED=true
            - ORDERER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@example.com/tls/ca.crt
            - ORDERER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@example.com/tls/client.crt
            - ORDERER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@example.com/tls/client.key
        volumes:
            - ../network-config/:/var/hyperledger/configs
            - ../crypto-config/ordererOrganizations/example.com/users:/var/hyperledger/users
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        command: orderer
        env_file: .env
        ports:
          - '7050'

    couchdb:
        image: hyperledger/fabric-couchdb

    peer:
        image: hyperledger/fabric-peer
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=net
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=deployment_behave
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_LOGGING_MSP=DEBUG
            # TLS settings
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
        volumes:
            - /var/run/:/host/var/run/
            - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
        command: peer node start
        env_file: .env
        ports:
            - '7051'
            - '7053'

